// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CalorieTrackingAppDB))]
    partial class CalorieTrackingAppDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Meyveler"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Sebzeler"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Süt Ve Süt Ürünleri"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Et ve Et Ürünleri"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Tatlılar"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Tahıllar"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Çerezler"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "İçecekler"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Unlu Mamuller"
                        });
                });

            modelBuilder.Entity("Entities.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"), 1L, 1);

                    b.Property<decimal>("Calorie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Calorie = 100m,
                            CategoryID = 3,
                            FoodName = "Sut",
                            ImagePath = "sut.jpg"
                        },
                        new
                        {
                            FoodID = 2,
                            Calorie = 70m,
                            CategoryID = 1,
                            FoodName = "Elma",
                            ImagePath = "elma.jpg"
                        },
                        new
                        {
                            FoodID = 3,
                            Calorie = 80m,
                            CategoryID = 4,
                            FoodName = "Hamsi",
                            ImagePath = "hamsi.jpg"
                        },
                        new
                        {
                            FoodID = 4,
                            Calorie = 150m,
                            CategoryID = 7,
                            FoodName = "Fındık",
                            ImagePath = "findik.jpg"
                        },
                        new
                        {
                            FoodID = 5,
                            Calorie = 95m,
                            CategoryID = 3,
                            FoodName = "Yogurt",
                            ImagePath = "yogurt.jpg"
                        },
                        new
                        {
                            FoodID = 6,
                            Calorie = 275m,
                            CategoryID = 3,
                            FoodName = "Beyaz Peynir",
                            ImagePath = "beyazpeynir.jpg"
                        },
                        new
                        {
                            FoodID = 7,
                            Calorie = 160m,
                            CategoryID = 3,
                            FoodName = "Yumurta",
                            ImagePath = "yumurta.jpg"
                        },
                        new
                        {
                            FoodID = 8,
                            Calorie = 26m,
                            CategoryID = 1,
                            FoodName = "Çilek",
                            ImagePath = "cilek.jpg"
                        },
                        new
                        {
                            FoodID = 9,
                            Calorie = 275m,
                            CategoryID = 1,
                            FoodName = "Kayısı",
                            ImagePath = "kayisi.jpg"
                        },
                        new
                        {
                            FoodID = 10,
                            Calorie = 52m,
                            CategoryID = 1,
                            FoodName = "Armut",
                            ImagePath = "armut.jpg"
                        },
                        new
                        {
                            FoodID = 11,
                            Calorie = 40m,
                            CategoryID = 1,
                            FoodName = "Kiraz",
                            ImagePath = "kiraz.jpg"
                        },
                        new
                        {
                            FoodID = 12,
                            Calorie = 41m,
                            CategoryID = 1,
                            FoodName = "İncir",
                            ImagePath = "incir.jpg"
                        },
                        new
                        {
                            FoodID = 13,
                            Calorie = 42.1m,
                            CategoryID = 1,
                            FoodName = "Greyfurt",
                            ImagePath = "greyfurt.jpg"
                        },
                        new
                        {
                            FoodID = 14,
                            Calorie = 63m,
                            CategoryID = 1,
                            FoodName = "Kivi",
                            ImagePath = "kivi.jpg"
                        },
                        new
                        {
                            FoodID = 15,
                            Calorie = 313m,
                            CategoryID = 5,
                            FoodName = "Muhallebi",
                            ImagePath = "muhallebi.jpg"
                        },
                        new
                        {
                            FoodID = 16,
                            Calorie = 267m,
                            CategoryID = 5,
                            FoodName = "Sütlaç",
                            ImagePath = "sutlac.jpg"
                        },
                        new
                        {
                            FoodID = 17,
                            Calorie = 501m,
                            CategoryID = 5,
                            FoodName = "Revani",
                            ImagePath = "revani.jpg"
                        },
                        new
                        {
                            FoodID = 18,
                            Calorie = 291m,
                            CategoryID = 5,
                            FoodName = "Profiterol",
                            ImagePath = "profiterol.jpg"
                        },
                        new
                        {
                            FoodID = 19,
                            Calorie = 371m,
                            CategoryID = 5,
                            FoodName = "Muzlu Puding",
                            ImagePath = "muzlupuding.jpg"
                        },
                        new
                        {
                            FoodID = 20,
                            Calorie = 600m,
                            CategoryID = 7,
                            FoodName = "Badem",
                            ImagePath = "badem.jpg"
                        },
                        new
                        {
                            FoodID = 21,
                            Calorie = 560m,
                            CategoryID = 7,
                            FoodName = "Fıstık",
                            ImagePath = "fistik.jpg"
                        },
                        new
                        {
                            FoodID = 22,
                            Calorie = 578m,
                            CategoryID = 7,
                            FoodName = "AyÇekirdeği",
                            ImagePath = "aycekirdegi.jpg"
                        },
                        new
                        {
                            FoodID = 23,
                            Calorie = 245m,
                            CategoryID = 7,
                            FoodName = "Kestane",
                            ImagePath = "kestane.jpg"
                        },
                        new
                        {
                            FoodID = 24,
                            Calorie = 549m,
                            CategoryID = 7,
                            FoodName = "Ceviz",
                            ImagePath = "ceviz.jpg"
                        },
                        new
                        {
                            FoodID = 25,
                            Calorie = 478m,
                            CategoryID = 7,
                            FoodName = "Patlamış Mısır",
                            ImagePath = "patlamismisir.jpg"
                        },
                        new
                        {
                            FoodID = 26,
                            Calorie = 47m,
                            CategoryID = 8,
                            FoodName = "Elma Suyu",
                            ImagePath = "elmasuyu.jpg"
                        },
                        new
                        {
                            FoodID = 27,
                            Calorie = 59m,
                            CategoryID = 8,
                            FoodName = "Kola",
                            ImagePath = "kola.jpg"
                        },
                        new
                        {
                            FoodID = 28,
                            Calorie = 3m,
                            CategoryID = 8,
                            FoodName = "Şekersiz Çay",
                            ImagePath = "sekersizcay.jpg"
                        },
                        new
                        {
                            FoodID = 29,
                            Calorie = 9m,
                            CategoryID = 8,
                            FoodName = "Şekersiz Kahve",
                            ImagePath = "sekersizkahve.jpg"
                        },
                        new
                        {
                            FoodID = 30,
                            Calorie = 45m,
                            CategoryID = 8,
                            FoodName = "Portakal Suyu",
                            ImagePath = "portakalsuyu.jpg"
                        },
                        new
                        {
                            FoodID = 31,
                            Calorie = 30m,
                            CategoryID = 8,
                            FoodName = "Soğuk Çay",
                            ImagePath = "sogukcay.jpg"
                        },
                        new
                        {
                            FoodID = 32,
                            Calorie = 46m,
                            CategoryID = 8,
                            FoodName = "Meyveli Soda",
                            ImagePath = "meyvelisoda.jpg"
                        },
                        new
                        {
                            FoodID = 33,
                            Calorie = 48m,
                            CategoryID = 8,
                            FoodName = "Fanta",
                            ImagePath = "fanta.jpg"
                        },
                        new
                        {
                            FoodID = 34,
                            Calorie = 270m,
                            CategoryID = 8,
                            FoodName = "Beyaz Ekmek",
                            ImagePath = "beyazekmek.jpg"
                        },
                        new
                        {
                            FoodID = 35,
                            Calorie = 180m,
                            CategoryID = 6,
                            FoodName = "Kepek Ekmek",
                            ImagePath = "kepekekmegi.jpg"
                        },
                        new
                        {
                            FoodID = 36,
                            Calorie = 470m,
                            CategoryID = 6,
                            FoodName = "Bisküvi",
                            ImagePath = "bisküvi.jpg"
                        },
                        new
                        {
                            FoodID = 37,
                            Calorie = 85m,
                            CategoryID = 6,
                            FoodName = "Haşlanmış Makarna",
                            ImagePath = "haslanmismakarna.jpg"
                        },
                        new
                        {
                            FoodID = 38,
                            Calorie = 314m,
                            CategoryID = 6,
                            FoodName = "Mercimek(Kuru)",
                            ImagePath = "mercimekkoftesi.jpg"
                        },
                        new
                        {
                            FoodID = 39,
                            Calorie = 257m,
                            CategoryID = 9,
                            FoodName = "Bazlama",
                            ImagePath = "bazlama.jpg"
                        },
                        new
                        {
                            FoodID = 40,
                            Calorie = 200m,
                            CategoryID = 9,
                            FoodName = "Mısır Ekmeği"
                        },
                        new
                        {
                            FoodID = 41,
                            Calorie = 280m,
                            CategoryID = 9,
                            FoodName = "Börek"
                        },
                        new
                        {
                            FoodID = 42,
                            Calorie = 480m,
                            CategoryID = 9,
                            FoodName = "Pide"
                        },
                        new
                        {
                            FoodID = 43,
                            Calorie = 224m,
                            CategoryID = 9,
                            FoodName = "Krep"
                        },
                        new
                        {
                            FoodID = 44,
                            Calorie = 462m,
                            CategoryID = 9,
                            FoodName = "Kruvasan"
                        },
                        new
                        {
                            FoodID = 45,
                            Calorie = 230m,
                            CategoryID = 9,
                            FoodName = "Su Böreği"
                        },
                        new
                        {
                            FoodID = 46,
                            Calorie = 132m,
                            CategoryID = 4,
                            FoodName = "Tavuk Izgara"
                        },
                        new
                        {
                            FoodID = 47,
                            Calorie = 446m,
                            CategoryID = 4,
                            FoodName = "Salam"
                        },
                        new
                        {
                            FoodID = 48,
                            Calorie = 250m,
                            CategoryID = 4,
                            FoodName = "Pastırma"
                        },
                        new
                        {
                            FoodID = 49,
                            Calorie = 452m,
                            CategoryID = 4,
                            FoodName = "Sucuk"
                        },
                        new
                        {
                            FoodID = 50,
                            Calorie = 180m,
                            CategoryID = 4,
                            FoodName = "Jambon"
                        },
                        new
                        {
                            FoodID = 51,
                            Calorie = 90m,
                            CategoryID = 2,
                            FoodName = "Taze Fasulye"
                        },
                        new
                        {
                            FoodID = 52,
                            Calorie = 40m,
                            CategoryID = 2,
                            FoodName = "Brokoli"
                        },
                        new
                        {
                            FoodID = 53,
                            Calorie = 25m,
                            CategoryID = 2,
                            FoodName = "Kabak"
                        },
                        new
                        {
                            FoodID = 54,
                            Calorie = 89m,
                            CategoryID = 2,
                            FoodName = "Bezelye"
                        },
                        new
                        {
                            FoodID = 55,
                            Calorie = 26m,
                            CategoryID = 2,
                            FoodName = "Ispanak"
                        },
                        new
                        {
                            FoodID = 56,
                            Calorie = 96m,
                            CategoryID = 2,
                            FoodName = "Taze Mısır"
                        },
                        new
                        {
                            FoodID = 57,
                            Calorie = 36m,
                            CategoryID = 2,
                            FoodName = "Bamya"
                        },
                        new
                        {
                            FoodID = 58,
                            Calorie = 14m,
                            CategoryID = 2,
                            FoodName = "Mantar"
                        },
                        new
                        {
                            FoodID = 59,
                            Calorie = 15m,
                            CategoryID = 2,
                            FoodName = "Marul"
                        },
                        new
                        {
                            FoodID = 60,
                            Calorie = 70m,
                            CategoryID = 3,
                            FoodName = "Mozarella"
                        },
                        new
                        {
                            FoodID = 61,
                            Calorie = 257m,
                            CategoryID = 3,
                            FoodName = "Tulum Peyniri"
                        },
                        new
                        {
                            FoodID = 62,
                            Calorie = 108m,
                            CategoryID = 3,
                            FoodName = "Koyun Sütü"
                        },
                        new
                        {
                            FoodID = 63,
                            Calorie = 349m,
                            CategoryID = 3,
                            FoodName = "Krem Peyniri"
                        },
                        new
                        {
                            FoodID = 64,
                            Calorie = 440m,
                            CategoryID = 3,
                            FoodName = "Parmesan Peyniri"
                        },
                        new
                        {
                            FoodID = 65,
                            Calorie = 108m,
                            CategoryID = 3,
                            FoodName = "Koyun Sütü"
                        },
                        new
                        {
                            FoodID = 66,
                            Calorie = 90m,
                            CategoryID = 3,
                            FoodName = "Lor Peyniri"
                        },
                        new
                        {
                            FoodID = 67,
                            Calorie = 125m,
                            CategoryID = 3,
                            FoodName = "Meyveli Yoğurt"
                        },
                        new
                        {
                            FoodID = 68,
                            Calorie = 55m,
                            CategoryID = 3,
                            FoodName = "Kefir"
                        },
                        new
                        {
                            FoodID = 69,
                            Calorie = 117m,
                            CategoryID = 3,
                            FoodName = "Cacık"
                        },
                        new
                        {
                            FoodID = 70,
                            Calorie = 50m,
                            CategoryID = 1,
                            FoodName = "Ananas"
                        },
                        new
                        {
                            FoodID = 71,
                            Calorie = 57m,
                            CategoryID = 1,
                            FoodName = "Ayva"
                        },
                        new
                        {
                            FoodID = 72,
                            Calorie = 43m,
                            CategoryID = 1,
                            FoodName = "Böğürtlen"
                        },
                        new
                        {
                            FoodID = 73,
                            Calorie = 42m,
                            CategoryID = 3,
                            FoodName = "Lİmonata"
                        },
                        new
                        {
                            FoodID = 74,
                            Calorie = 42m,
                            CategoryID = 3,
                            FoodName = "Gazoz"
                        },
                        new
                        {
                            FoodID = 75,
                            Calorie = 148m,
                            CategoryID = 3,
                            FoodName = "Boza"
                        },
                        new
                        {
                            FoodID = 76,
                            Calorie = 349m,
                            CategoryID = 3,
                            FoodName = "Milkshake"
                        },
                        new
                        {
                            FoodID = 77,
                            Calorie = 1m,
                            CategoryID = 3,
                            FoodName = "Diyet Kola"
                        },
                        new
                        {
                            FoodID = 78,
                            Calorie = 488m,
                            CategoryID = 5,
                            FoodName = "Kurabiye"
                        },
                        new
                        {
                            FoodID = 79,
                            Calorie = 164m,
                            CategoryID = 5,
                            FoodName = "Kabak Tatlısı"
                        },
                        new
                        {
                            FoodID = 80,
                            Calorie = 411m,
                            CategoryID = 5,
                            FoodName = "Badem Ezmesi"
                        },
                        new
                        {
                            FoodID = 81,
                            Calorie = 30m,
                            CategoryID = 1,
                            FoodName = "Karpuz"
                        },
                        new
                        {
                            FoodID = 82,
                            Calorie = 83m,
                            CategoryID = 1,
                            FoodName = "Nar"
                        },
                        new
                        {
                            FoodID = 83,
                            Calorie = 34m,
                            CategoryID = 1,
                            FoodName = "Kavun"
                        },
                        new
                        {
                            FoodID = 84,
                            Calorie = 43m,
                            CategoryID = 2,
                            FoodName = "Kırmızı Pancar"
                        },
                        new
                        {
                            FoodID = 85,
                            Calorie = 25m,
                            CategoryID = 2,
                            FoodName = "Patlıcan"
                        },
                        new
                        {
                            FoodID = 86,
                            Calorie = 115m,
                            CategoryID = 2,
                            FoodName = "Siyah Zeytin"
                        },
                        new
                        {
                            FoodID = 87,
                            Calorie = 25m,
                            CategoryID = 2,
                            FoodName = "Roka"
                        },
                        new
                        {
                            FoodID = 88,
                            Calorie = 31m,
                            CategoryID = 5,
                            FoodName = "Rezene"
                        },
                        new
                        {
                            FoodID = 89,
                            Calorie = 195m,
                            CategoryID = 3,
                            FoodName = "Kahve Kreması"
                        },
                        new
                        {
                            FoodID = 90,
                            Calorie = 121m,
                            CategoryID = 4,
                            FoodName = "Antrikot"
                        },
                        new
                        {
                            FoodID = 91,
                            Calorie = 189m,
                            CategoryID = 4,
                            FoodName = "Hindi"
                        },
                        new
                        {
                            FoodID = 92,
                            Calorie = 266m,
                            CategoryID = 4,
                            FoodName = "Tavuk Kanadı"
                        },
                        new
                        {
                            FoodID = 93,
                            Calorie = 246m,
                            CategoryID = 6,
                            FoodName = "Yulaf Kepeği"
                        },
                        new
                        {
                            FoodID = 94,
                            Calorie = 281m,
                            CategoryID = 6,
                            FoodName = "Çavdar Tohumu"
                        },
                        new
                        {
                            FoodID = 95,
                            Calorie = 366m,
                            CategoryID = 6,
                            FoodName = "Mısır İrmiği"
                        },
                        new
                        {
                            FoodID = 96,
                            Calorie = 553m,
                            CategoryID = 7,
                            FoodName = "Kaju"
                        },
                        new
                        {
                            FoodID = 97,
                            Calorie = 267m,
                            CategoryID = 7,
                            FoodName = "Leblebi"
                        },
                        new
                        {
                            FoodID = 98,
                            Calorie = 57m,
                            CategoryID = 8,
                            FoodName = " Latte "
                        },
                        new
                        {
                            FoodID = 99,
                            Calorie = 37m,
                            CategoryID = 8,
                            FoodName = "Smoothie"
                        },
                        new
                        {
                            FoodID = 100,
                            Calorie = 89m,
                            CategoryID = 8,
                            FoodName = "Sıcak Çİkolata"
                        });
                });

            modelBuilder.Entity("Entities.Models.Food_User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("Meal")
                        .HasColumnType("int");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("UserID");

                    b.ToTable("Foods_Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3141),
                            FoodID = 1,
                            Meal = 1,
                            Number = (byte)2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3143),
                            FoodID = 2,
                            Meal = 1,
                            Number = (byte)2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3144),
                            FoodID = 3,
                            Meal = 1,
                            Number = (byte)3,
                            UserID = 2
                        },
                        new
                        {
                            ID = 4,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3145),
                            FoodID = 4,
                            Meal = 1,
                            Number = (byte)3,
                            UserID = 2
                        },
                        new
                        {
                            ID = 5,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3146),
                            FoodID = 7,
                            Meal = 1,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 6,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3147),
                            FoodID = 35,
                            Meal = 1,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 7,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3148),
                            FoodID = 47,
                            Meal = 1,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 8,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3149),
                            FoodID = 86,
                            Meal = 1,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 9,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3150),
                            FoodID = 86,
                            Meal = 2,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 10,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3151),
                            FoodID = 33,
                            Meal = 2,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 11,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3152),
                            FoodID = 46,
                            Meal = 2,
                            Number = (byte)1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 12,
                            Day = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3153),
                            FoodID = 51,
                            Meal = 2,
                            Number = (byte)1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<int?>("Activity")
                        .HasColumnType("int");

                    b.Property<double?>("BasalMetabolicRate")
                        .HasPrecision(4, 1)
                        .HasColumnType("float(4)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<double?>("GoalWeight")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasPrecision(3, 2)
                        .HasColumnType("float(3)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Activity = 3,
                            BirthDate = new DateTime(1998, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRegistration = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(3984),
                            FirstName = "İrem",
                            Gender = 1,
                            GoalWeight = 48.0,
                            Height = 1.6000000000000001,
                            Password = "123",
                            UserName = "iremilgin@gmail.com",
                            Weight = 50.0
                        },
                        new
                        {
                            UserID = 2,
                            Activity = 1,
                            BirthDate = new DateTime(1998, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRegistration = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(4040),
                            FirstName = "İlbey",
                            Gender = 2,
                            GoalWeight = 80.0,
                            Height = 1.8,
                            Password = "1234",
                            UserName = "ilbeyikiz@gmail.com",
                            Weight = 86.0
                        },
                        new
                        {
                            UserID = 3,
                            Activity = 1,
                            BirthDate = new DateTime(1992, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRegistration = new DateTime(2023, 5, 15, 0, 32, 37, 519, DateTimeKind.Local).AddTicks(4046),
                            FirstName = "Yunus",
                            Gender = 2,
                            GoalWeight = 75.0,
                            Height = 1.77,
                            Password = "1206",
                            UserName = "yunuskilic@gmail.com",
                            Weight = 78.0
                        });
                });

            modelBuilder.Entity("Entities.Models.Food", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Food_User", b =>
                {
                    b.HasOne("Entities.Models.Food", "Food")
                        .WithMany("Foods_Users")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Foods_Users")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Entities.Models.Food", b =>
                {
                    b.Navigation("Foods_Users");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Foods_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
